### ISSUE TITLE
Wrong install url at web page

### ISSUE THREAD

**Issue by arnoldcui** [argoproj/argo#3824]
## Summary 

Wrong install url at web page

![image](https://user-images.githubusercontent.com/40977489/90709964-f5502780-e2cf-11ea-8646-2f0629d794c6.png)

https://argoproj.github.io/argo/quick-start/

**Comment by alexec** [comment]
Should be fixed now.

**Comment by arnoldcui** [comment]
![image](https://user-images.githubusercontent.com/40977489/90843149-918f3280-e393-11ea-860f-eff060eac32b.png)
![image](https://user-images.githubusercontent.com/40977489/90843382-111d0180-e394-11ea-9cc1-b6b865e14179.png)
![image](https://user-images.githubusercontent.com/40977489/90843421-285bef00-e394-11ea-8147-f37893a114ab.png)

Still not fixed.
And didn't find any change about `quick-start-postgres.yml` in #3827
